#include <dme/input/input_key.h>
namespace dme::input {

	InputKeyMap::InputKeyMap(const InputKey key, stdstr name, const sint real, InputKeyType type) : key(key), name(std::move(name)), real(real), type(type) {}
	const InputKeyMap& InputKeyMap::ToMap(InputKey key) {
		return allInputKeyMap[static_cast<uint>(key)];
	}
	const InputKeyMap InputKeyMap::allInputKeyMap[static_cast<uint>(InputKey::AllInputKeyCount)] = {
		InputKeyMap(InputKey::none, "None", GLFW_KEY_UNKNOWN),
		InputKeyMap(InputKey::a, "A", GLFW_KEY_A),
		InputKeyMap(InputKey::b, "B", GLFW_KEY_B),
		InputKeyMap(InputKey::c, "C", GLFW_KEY_C),
		InputKeyMap(InputKey::d, "D", GLFW_KEY_D),
		InputKeyMap(InputKey::e, "E", GLFW_KEY_E),
		InputKeyMap(InputKey::f, "F", GLFW_KEY_F),
		InputKeyMap(InputKey::g, "G", GLFW_KEY_G),
		InputKeyMap(InputKey::h, "H", GLFW_KEY_H),
		InputKeyMap(InputKey::i, "I", GLFW_KEY_I),
		InputKeyMap(InputKey::j, "J", GLFW_KEY_J),
		InputKeyMap(InputKey::k, "K", GLFW_KEY_K),
		InputKeyMap(InputKey::l, "L", GLFW_KEY_L),
		InputKeyMap(InputKey::m, "M", GLFW_KEY_M),
		InputKeyMap(InputKey::n, "N", GLFW_KEY_N),
		InputKeyMap(InputKey::o, "O", GLFW_KEY_O),
		InputKeyMap(InputKey::p, "P", GLFW_KEY_P),
		InputKeyMap(InputKey::q, "Q", GLFW_KEY_Q),
		InputKeyMap(InputKey::r, "R", GLFW_KEY_R),
		InputKeyMap(InputKey::s, "S", GLFW_KEY_S),
		InputKeyMap(InputKey::t, "T", GLFW_KEY_T),
		InputKeyMap(InputKey::u, "U", GLFW_KEY_U),
		InputKeyMap(InputKey::v, "V", GLFW_KEY_V),
		InputKeyMap(InputKey::w, "W", GLFW_KEY_W),
		InputKeyMap(InputKey::x, "X", GLFW_KEY_X),
		InputKeyMap(InputKey::y, "Y", GLFW_KEY_Y),
		InputKeyMap(InputKey::z, "Z", GLFW_KEY_Z),
		InputKeyMap(InputKey::k0, "0", GLFW_KEY_0),
		InputKeyMap(InputKey::k1, "1", GLFW_KEY_1),
		InputKeyMap(InputKey::k2, "2", GLFW_KEY_2),
		InputKeyMap(InputKey::k3, "3", GLFW_KEY_3),
		InputKeyMap(InputKey::k4, "4", GLFW_KEY_4),
		InputKeyMap(InputKey::k5, "5", GLFW_KEY_5),
		InputKeyMap(InputKey::k6, "6", GLFW_KEY_6),
		InputKeyMap(InputKey::k7, "7", GLFW_KEY_7),
		InputKeyMap(InputKey::k8, "8", GLFW_KEY_8),
		InputKeyMap(InputKey::k9, "9", GLFW_KEY_9),
		InputKeyMap(InputKey::f1, "F1", GLFW_KEY_F1),
		InputKeyMap(InputKey::f2, "F2", GLFW_KEY_F2),
		InputKeyMap(InputKey::f3, "F3", GLFW_KEY_F3),
		InputKeyMap(InputKey::f4, "F4", GLFW_KEY_F4),
		InputKeyMap(InputKey::f5, "F5", GLFW_KEY_F5),
		InputKeyMap(InputKey::f6, "F6", GLFW_KEY_F6),
		InputKeyMap(InputKey::f7, "F7", GLFW_KEY_F7),
		InputKeyMap(InputKey::f8, "F8", GLFW_KEY_F8),
		InputKeyMap(InputKey::f9, "F9", GLFW_KEY_F9),
		InputKeyMap(InputKey::f10, "F10", GLFW_KEY_F10),
		InputKeyMap(InputKey::f11, "F11", GLFW_KEY_F11),
		InputKeyMap(InputKey::f12, "F12", GLFW_KEY_F12),
		InputKeyMap(InputKey::f13, "F13", GLFW_KEY_F13),
		InputKeyMap(InputKey::f14, "F14", GLFW_KEY_F14),
		InputKeyMap(InputKey::f15, "F15", GLFW_KEY_F15),
		InputKeyMap(InputKey::f16, "F16", GLFW_KEY_F16),
		InputKeyMap(InputKey::f17, "F17", GLFW_KEY_F17),
		InputKeyMap(InputKey::f18, "F18", GLFW_KEY_F18),
		InputKeyMap(InputKey::f19, "F19", GLFW_KEY_F19),
		InputKeyMap(InputKey::f20, "F20", GLFW_KEY_F20),
		InputKeyMap(InputKey::f21, "F21", GLFW_KEY_F21),
		InputKeyMap(InputKey::f22, "F22", GLFW_KEY_F22),
		InputKeyMap(InputKey::f23, "F23", GLFW_KEY_F23),
		InputKeyMap(InputKey::f24, "F24", GLFW_KEY_F24),
		InputKeyMap(InputKey::f25, "F25", GLFW_KEY_F25),
		InputKeyMap(InputKey::space, "SPACE", GLFW_KEY_SPACE),
		InputKeyMap(InputKey::grave, "`", GLFW_KEY_GRAVE_ACCENT),
		InputKeyMap(InputKey::minus, "-", GLFW_KEY_MINUS),
		InputKeyMap(InputKey::equal, "=", GLFW_KEY_EQUAL),
		InputKeyMap(InputKey::leftBracket, "[", GLFW_KEY_LEFT_BRACKET),
		InputKeyMap(InputKey::rightBracket, "]", GLFW_KEY_RIGHT_BRACKET),
		InputKeyMap(InputKey::backslash, "\\", GLFW_KEY_BACKSLASH),
		InputKeyMap(InputKey::semicolon, ";", GLFW_KEY_SEMICOLON),
		InputKeyMap(InputKey::apostrophe, "'", GLFW_KEY_APOSTROPHE),
		InputKeyMap(InputKey::comma, ",", GLFW_KEY_COMMA),
		InputKeyMap(InputKey::period, ".", GLFW_KEY_PERIOD),
		InputKeyMap(InputKey::slash, "/", GLFW_KEY_SLASH),
		InputKeyMap(InputKey::leftShift, "LEFT SHIFT", GLFW_KEY_LEFT_SHIFT),
		InputKeyMap(InputKey::leftControl, "LEFT CONTROL", GLFW_KEY_LEFT_CONTROL),
		InputKeyMap(InputKey::leftAlt, "LEFT ALT", GLFW_KEY_LEFT_ALT),
		InputKeyMap(InputKey::leftSuper, "LEFT SUPER", GLFW_KEY_LEFT_SUPER),
		InputKeyMap(InputKey::rightShift, "RIGHT SHIFT", GLFW_KEY_RIGHT_SHIFT),
		InputKeyMap(InputKey::rightControl, "RIGHT CONTROL", GLFW_KEY_RIGHT_CONTROL),
		InputKeyMap(InputKey::rightAlt, "RIGHT ALT", GLFW_KEY_RIGHT_ALT),
		InputKeyMap(InputKey::rightSuper, "RIGHT SUPER", GLFW_KEY_RIGHT_SUPER),
		InputKeyMap(InputKey::menu, "MENU", GLFW_KEY_MENU),
		InputKeyMap(InputKey::escape, "ESCAPE", GLFW_KEY_ESCAPE),
		InputKeyMap(InputKey::tab, "TAB", GLFW_KEY_TAB),
		InputKeyMap(InputKey::backspace, "BACKSPACE", GLFW_KEY_BACKSPACE),
		InputKeyMap(InputKey::enter, "ENTER", GLFW_KEY_ENTER),
		InputKeyMap(InputKey::up, "↑", GLFW_KEY_UP),
		InputKeyMap(InputKey::down, "↓", GLFW_KEY_DOWN),
		InputKeyMap(InputKey::left, "←", GLFW_KEY_LEFT),
		InputKeyMap(InputKey::right, "→", GLFW_KEY_RIGHT),
		InputKeyMap(InputKey::insert, "INSERT", GLFW_KEY_INSERT),
		InputKeyMap(InputKey::home, "HOME", GLFW_KEY_HOME),
		InputKeyMap(InputKey::del, "DELETE", GLFW_KEY_DELETE),
		InputKeyMap(InputKey::end, "END", GLFW_KEY_END),
		InputKeyMap(InputKey::pageUp, "PAGE UP", GLFW_KEY_PAGE_UP),
		InputKeyMap(InputKey::pageDown, "PAGE DOWN", GLFW_KEY_PAGE_DOWN),
		InputKeyMap(InputKey::printScreen, "PRINT SCREEN", GLFW_KEY_PRINT_SCREEN),
		InputKeyMap(InputKey::pause, "PAUSE", GLFW_KEY_PAUSE),
		InputKeyMap(InputKey::capsLock, "CAPS LOCK", GLFW_KEY_CAPS_LOCK),
		InputKeyMap(InputKey::scrollLock, "SCROLL LOCK", GLFW_KEY_SCROLL_LOCK),
		InputKeyMap(InputKey::numLock, "NUM LOCK", GLFW_KEY_NUM_LOCK),
		InputKeyMap(InputKey::kp0, "KEYPAD 0", GLFW_KEY_KP_0),
		InputKeyMap(InputKey::kp1, "KEYPAD 1", GLFW_KEY_KP_1),
		InputKeyMap(InputKey::kp2, "KEYPAD 2", GLFW_KEY_KP_2),
		InputKeyMap(InputKey::kp3, "KEYPAD 3", GLFW_KEY_KP_3),
		InputKeyMap(InputKey::kp4, "KEYPAD 4", GLFW_KEY_KP_4),
		InputKeyMap(InputKey::kp5, "KEYPAD 5", GLFW_KEY_KP_5),
		InputKeyMap(InputKey::kp6, "KEYPAD 6", GLFW_KEY_KP_6),
		InputKeyMap(InputKey::kp7, "KEYPAD 7", GLFW_KEY_KP_7),
		InputKeyMap(InputKey::kp8, "KEYPAD 8", GLFW_KEY_KP_8),
		InputKeyMap(InputKey::kp9, "KEYPAD 9", GLFW_KEY_KP_9),
		InputKeyMap(InputKey::kpDivide, "KEYPAD DIVIDE", GLFW_KEY_KP_DIVIDE),
		InputKeyMap(InputKey::kpMultiply, "KEYPAD MULTIPLY", GLFW_KEY_KP_MULTIPLY),
		InputKeyMap(InputKey::kpSubtract, "KEYPAD SUBTRACT", GLFW_KEY_KP_SUBTRACT),
		InputKeyMap(InputKey::kpAdd, "KEYPAD ADD", GLFW_KEY_KP_ADD),
		InputKeyMap(InputKey::kpEqual, "KEYPAD EQUAL", GLFW_KEY_KP_EQUAL),
		InputKeyMap(InputKey::kpDecimal, "KEYPAD DECIMAL", GLFW_KEY_KP_DECIMAL),
		InputKeyMap(InputKey::kpEnter, "KEYPAD ENTER", GLFW_KEY_KP_ENTER),
		InputKeyMap(InputKey::mouseLeftButton, "MOUSE LEFT BUTTON", GLFW_MOUSE_BUTTON_1, InputKeyType::mouse),
		InputKeyMap(InputKey::mouseRightButton, "MOUSE RIGHT BUTTON", GLFW_MOUSE_BUTTON_2, InputKeyType::mouse),
		InputKeyMap(InputKey::mouseMiddleButton, "MOUSE MIDDLE BUTTON", GLFW_MOUSE_BUTTON_3, InputKeyType::mouse),
		InputKeyMap(InputKey::mouseButton4, "MOUSE BUTTON 4", GLFW_MOUSE_BUTTON_4, InputKeyType::mouse),
		InputKeyMap(InputKey::mouseButton5, "MOUSE BUTTON 5", GLFW_MOUSE_BUTTON_5, InputKeyType::mouse),
		InputKeyMap(InputKey::mouseButton6, "MOUSE BUTTON 6", GLFW_MOUSE_BUTTON_6, InputKeyType::mouse),
		InputKeyMap(InputKey::mouseButton7, "MOUSE BUTTON 7", GLFW_MOUSE_BUTTON_7, InputKeyType::mouse),
		InputKeyMap(InputKey::mouseButton8, "MOUSE BUTTON 8", GLFW_MOUSE_BUTTON_8, InputKeyType::mouse),
	};

	std::unordered_map<sint, const InputKeyMap> InputKeyMap::allKeyMap = {};
	std::unordered_map<sint, const InputKeyMap> InputKeyMap::allMouseButtonMap = {};


}